// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrzqNo8hRzRkCA8t6E1_YWseiRgRqS9FE',
    appId: '1:38235317642:web:0cdaa3b6401be99849d473',
    messagingSenderId: '38235317642',
    projectId: 'flutterschool-70d7a',
    authDomain: 'flutterschool-70d7a.firebaseapp.com',
    databaseURL: 'https://flutterschool-70d7a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutterschool-70d7a.appspot.com',
    measurementId: 'G-GC44CD7JT0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEi3Nj78MYDN5wiOGMrDBRv5QWTeEZAm8',
    appId: '1:38235317642:android:e5fdb0ecdd04d4a349d473',
    messagingSenderId: '38235317642',
    projectId: 'flutterschool-70d7a',
    databaseURL: 'https://flutterschool-70d7a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutterschool-70d7a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1URUjTB8XR8MMbtcIoAqy_yJijrtwh8s',
    appId: '1:38235317642:ios:b7860be88374b04049d473',
    messagingSenderId: '38235317642',
    projectId: 'flutterschool-70d7a',
    databaseURL: 'https://flutterschool-70d7a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutterschool-70d7a.appspot.com',
    androidClientId: '38235317642-lb8pkhhvjb28nr9adfk9cemjnklnbu15.apps.googleusercontent.com',
    iosClientId: '38235317642-4i8ul6m33g6ljpap0bk2b46lv05k1j79.apps.googleusercontent.com',
    iosBundleId: 'com.oyc0401.flutterschool',
  );
}
